### ISSUE TITLE
Make depth buffer bits configurable

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#101]
For my current game I need a depth buffer of at least 24 bits and need to enforce this on window creation. At the moment the glfw depth buffer bit hint is not called at all. Please add the depth buffer bit option to `WindowOptions` and call the associated glfw hint method. The default value may be GLFW_DONT_CARE to keep compatibility.

**Comment by Perksey** [comment]
This one will have to be done by the community. Please propose a PR adding the properties required to the `IMonitor` interface. Thanks in advance!

**Comment by Pyrdacor** [comment]
I noticed that the depth buffer bits are not part of the video mode nor monitor in glfw. Moreover it is only a soft constraint. Should I add the VideoMode stuff for resolution and refresh rate and support specifying the depth buffer bits only on windows creation?

**Comment by Perksey** [comment]
Oh I just realized you should be working on the `views` branch as my PR has not been merged yet. Here there are already monitor APIs to some extent, but they currently do not have the bit depth properties

**Comment by Perksey** [comment]
Also change the VideoMode property to `get` in `IViewOptions` and `get set` in `ViewOptions` and `WindowOptions`

**Comment by Perksey** [comment]
Resolved in #102.
