### ISSUE TITLE
PhysicalDeviceMemoryProperties and similar structures should use fixed buffers

### ISSUE THREAD

**Issue by sunkin351** [Ultz/Silk.NET#103]
The C declaration goes as follows:
```c
typedef struct VkPhysicalDeviceMemoryProperties {
    uint32_t        memoryTypeCount;
    VkMemoryType    memoryTypes[VK_MAX_MEMORY_TYPES];
    uint32_t        memoryHeapCount;
    VkMemoryHeap    memoryHeaps[VK_MAX_MEMORY_HEAPS];
} VkPhysicalDeviceMemoryProperties;
```
`MemoryTypes` and `MemoryHeaps` members should be fixed buffers rather than a collection of fields inside the structure.

**Comment by Perksey** [comment]
Looking at this now, turns out we can't use fixed buffers for these types as you can only create fixed buffers to bool, byte, char, short, int, long, sbyte, ushort, uint, ulong, float, or double types.

I don't think we're going to be able to fix this, sorry :|
