### ISSUE TITLE
Headless mode 

### ISSUE THREAD

**Issue by mikart143** [Ultz/Silk.NET#107]
- [ x] I have definitely checked that there are no proposals for this already in the [proposals folder](https://github.com/Ultz/Silk.NET-Docs)

# Summary of feature
It is not a thing that will be used commonly but for some people it will be useful. Creating headless mode could be just use for handling input from controllers. Since Silk.net is very cross platform this could be beneficial.

What headless mean in my point of view. Do not create a window.

# Comments

**Comment by Perksey** [comment]
Ah so you mean using input independently of windowing? I'm not entirely sure how this will work, especially considering GLFW requires a window present to record input (to my knowledge).

**Comment by mikart143** [comment]
Yes, that it's what I am thinking about. Sorry but I am not to familiar with these technologies. If this is not possible then there is no need to talk about it

**Comment by Perksey** [comment]
Due to technical restrictions within GLFW (you can't use some of the input functions without a window), we've decided that we can't feasibly implement this in an efficient way and sadly won't be able to get this in :(

Sorry about that :(
