### ISSUE TITLE
Preview4 GL.GetApi throws exception

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#123]
# Summary
A call to GL.GetApi throws the following exception:

    System.TypeInitializationException
      HResult=0x80131534
      Message = The type initializer for 'Silk.NET.OpenGL.GL' threw an exception.
      Source = Silk.NET.OpenGL
      StackTrace:
       at Silk.NET.OpenGL.GL.GetApi()
       ...
      InnerException:
        KeyNotFoundException: The given key 'Silk.NET.Core.Loader.GLSymbolLoader' was not present in the dictionary.

# Steps to reproduce
- Platform: Desktop, Windows 7
- Framework Version: .NET Core 3.1
1. I created a window with `GlfwPlatform.Instance.GetView(options) as IWindow`.
2. GL.GetApi is then called in a static ctor of some class. But the call happens only after everything is initialized as the static ctor is invoked when I first try to access the GL context (which worked in preview3).

# Comments
The assembly in which is the call to GetApi is a .NET Standard 2.0 DLL and only has Silk.NET.OpenGL as a nuget reference. The main executable is a .NET Core 3.1 EXE which references the mentioned DLL as well as most Silk.NET nuget packages (except for Vulkan). All referenced versions are preview4.

**Comment by Perksey** [comment]
You are not creating a GL context using the supported APIs. You need to use the `Window` class
(i.e. `Window.GetView()`)

Using the GlfwPlatform directly is not supported.

**Comment by Pyrdacor** [comment]
Thanks for the info. After view/window rework I was a bit confused how I have to do things now. Ok I made it working now.
