### ISSUE TITLE
Cursor mode is not fully implemented :/

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#124]
# Summary of feature
Cursor mode enum is there but it is not used yet nor is it changeable.

# Comments
Basically I forgot to add this functionality in my previous PR. Shame on me. :( This has still to be implemented. Shouldn't be much of work hopefully.

**Comment by Perksey** [comment]
This will need an extra PR, so if you find time for one that'll be awesome! :)

**Comment by Pyrdacor** [comment]
Yeah I can do it. But most likely not in the next few days. I'll start the PR later if nobody had already done so.

**Comment by Perksey** [comment]
The working group is all tied up in other projects atm, so you should be all clear to make a PR.
