### ISSUE TITLE
Add a ClearCurrent method to IView or IWindowPlatform

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#131]
- [x] I have definitely checked that there are no proposals for this already in the [proposals folder](https://github.com/Ultz/Silk.NET-Docs)

# Summary of feature
Currently there's no way to clear a thread's current context and initiate a pipeline flush (i.e. `glfwMakeContextCurrent(NULL)`. One should be added.

# Comments
I'm not sure whether to put this in IView or IWindowPlatform.

**Comment by Perksey** [comment]
@Ultz/silk-working-group I'm not sure whether to put this in IView or IWindowPlatform. Which do you think is better
```cs
_window.MakeCurrent();
Silk.NET.Windowing.Window.ClearContext();
```
or
```cs
_window.MakeCurrent();
_window.ClearContext();
```

**Comment by devvoid** [comment]
I think the latter makes more sense.

**Comment by maxilevi** [comment]
The second one looks better to me too though it feels strange since you are changing a global status via an instance.

**Comment by Perksey** [comment]
Yeah I agree which is why I was torn in where it would go, but I think the 2nd one is better because it deals with special cases such as those where you are using two different windowing platforms.

**Comment by Pyrdacor** [comment]
The second one makes sense but only if it holds the current context. I would prefer an additional static method if you want to clear the context without condition. In this case I wouldn't like the second way with an instance. Cause it has nothing to do with this instance. In case of two window platforms I would prefer internal logic to handle it and not the instance approach.

**Comment by frederikja163** [comment]
First one makes the most sense, second one is the cleanest. Depends on what we want out of those two tbh.

**Comment by Perksey** [comment]
I think we should put it in IView as that's where the user would likely expect to find it, however nonsensical.

**Comment by Pyrdacor** [comment]
How about this: You add the `ClearCurrent` method to `IView` as mentioned. But it only clears the context (calls MakeCurrent with null) if its context is currently active (`if (ActiveView == this) MakeCurrent(null)`). This would add the need to store the `IView` with the current context in a static variable though. But it would be a nice feature to be able to access the "current" `IView`. So a static property like `ActiveView` in the `IView` interface would be nice. Moreover you can clear the context globally by calling `IView.ActiveWindow.ClearContext()`. But you can also clear the context of a specific window with the given instance as well and don't clear the context if another view holds the current context. I think this would be nicer and would make more sense.

**Comment by Perksey** [comment]
That's brilliant! As for accessing the active view, that'll be very hard to implement given that we need to construct an internal map of `WindowHandle*`s to `IView`s. It could be done though, perhaps in the `Silk.NET.Windowing.Extensions` package. As a compromise, we could also introduce a `IsCurrent` property.

**Comment by Pyrdacor** [comment]
If we could enforce each `IView.MakeCurrent` implementation to set the `ActiveView` to `this`, it would be much easier. But this would be only possible within our own `IView` implementations. This would also need no internal map imho.

**Comment by Pyrdacor** [comment]
`IsCurrent` would also be nice. But I would add this simply as an extension as it is simply `ActiveView == theViewToCheck`.

**Comment by Perksey** [comment]
Another thing is that multiple views can be current at one time i.e. on different threads. I think the best solution is as follows:

- Add `IView.ClearCurrent` which will call `glfwClearCurrentContext` if `glfwGetCurrentContext` is the current view.
- Add IsCurrent which will return true if `glfwGetCurrentContext` is the current view.
- Add `IWindowPlatform.ClearCurrentContexts` (and `Window.ClearCurrentContexts`) which will call `glfwClearCurrentContext` without running any prerequisite checks.

**Comment by Pyrdacor** [comment]
Yes this sounds reasonable. And then one could just query the "active views" by searching for the views with `IsCurrent == true` inside a collection of his choice (e.g. a self-managed map).

**Comment by Perksey** [comment]
> Yes this sounds reasonable. And then one could just query the "active views" by searching for the views with IsCurrent == true inside a collection of his choice (e.g. a self-managed map).

Perhaps we could add `ActiveView` to the `WindowManager` class in `Silk.NET.Windowing.Extensions` (not a lot of people know about this class :P, so it's worth a look if you're dealing with multiple views)

**Comment by Pyrdacor** [comment]
You got me. ;D After a look at it I agree. It's perfect for the addition of `ActiveViews`.

**Comment by Perksey** [comment]
I actually can't remember whether or not I moved WindowManager over to the views API, but that's subject for another issue. To summarize:

- Add `IView.ClearCurrent` which will call `glfwClearCurrentContext` if `IsCurrent` is `true`.
- Add `IsCurrent` which will return true if `glfwGetCurrentContext` is the current view.
- Add `IWindowPlatform.ClearCurrentContexts` (and `Window.ClearCurrentContexts`) which will call `glfwClearCurrentContext` without running any prerequisite checks.
- Add `ActiveWindows` to `WindowManager`
