### ISSUE TITLE
Closing event is not triggered when using GlfwWindow.Close

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#132]
# Summary
The closing event is not triggered when the `Close` method of the window/view is called (here the GlfwWindow implementation).

# Comments
I think the problem is this code in _Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs_:

    public static void Run(this IView view)
    {
        view.Initialize();
        while (!view.IsClosing)
        {
            view.DoEvents();
            view.DoUpdate();
            view.DoRender();
        }
        view.Reset();
    }

If the "close flag" is set by clicking the close button of the window, I guess it happens somewhere in `DoEvents` and then the closing event is triggered there too.

But if I call the `Close` method this will most likely happen in `DoUpdate` or `DoRender` (or better in the event handlers of the events they raise). So `view.IsClosing` is `true` and the next check will fail (the while loop won't run again). But then `DoEvents` won't be called anymore and so the closing event will never be raised in that case.

**Comment by Perksey** [comment]
Odd. If I remember correctly the close event is triggered by GLFW using some sort of callback, I’ll check when I get back home (walking the dog at the moment)

**Comment by Perksey** [comment]
Ah I see. We need another DoEvents call so GLFW triggers the close.

**Comment by Pyrdacor** [comment]
Yes it is. But I guess the callbacks are only called when glfwPollEvents is called.

**Comment by Pyrdacor** [comment]
> 
> 
> Ah I see. We need another DoEvents call so GLFW triggers the close.

Exactly

**Comment by Pyrdacor** [comment]
Got some time to test this and it is still an issue in 1.1.0. Is this fix included in 1.1.0? Here is some minimal code to reproducethe problem:

```cs
using System;
using System.Linq;
using Silk.NET.Input;
using Silk.NET.Input.Common;
using Silk.NET.Windowing.Common;
using Silk.NET.Windowing.Desktop;

namespace TestSilkWindow
{
    class Program
    {
        static IWindow silkWindow;

        static void Main()
        {
            using (var window = GlfwPlatform.Instance.CreateWindow(WindowOptions.Default))
            {
                silkWindow = window;
                window.Load += Window_Load;
                window.Run();
            }
        }

        private static void Window_Load()
        {
            silkWindow.CreateInput().Keyboards.First().KeyDown += Program_KeyDown;
            silkWindow.Closing += SilkWindow_Closing;
        }

        private static void Program_KeyDown(IKeyboard arg1, Key arg2, int arg3)
        {
            if (arg2 == Key.A)
                silkWindow.Close();
        }

        private static void SilkWindow_Closing()
        {
            Console.WriteLine("Closing");
        }
    }
}
```

When you close with window's close button the string "Closing" is printed. But if you hit the A key the window is closed without printing it.

**Comment by Perksey** [comment]
Interesting. This might be a GLFW issue, in which case we should stop using GLFW for the closing event.

**Comment by Perksey** [comment]
Fixed this yesterday and completely forgot about - it will be in the next patch update. We're having an interim release because there's some QoL fixes we must get in ASAP.

**Comment by Perksey** [comment]
This should be fixed, can you confirm?
