### ISSUE TITLE
TexParameterI overloads in preview 5

### ISSUE THREAD

**Issue by ceranco** [Ultz/Silk.NET#135]
# Summary
In **preview 4**, there was an overload for `GL.TexParameterI` that accepted an `int`:
```cs
gl.TexParameterI(GLEnum.Texture2D, GLEnum.TextureWrapS, (int)GLEnum.Repeat);
```

In **preview 5** however, this overload was removed and there now overloads that only accept `int*` or `ref int`:
```cs
int repeat = (int)GLEnum.Repeat;
gl.TexParameterI(GLEnum.Texture2D, GLEnum.TextureWrapS, ref repeat);
```
This makes it pretty cumbersome to use, because each parameter must first be saved in variable.

Is there any chance of getting the first overload back?

**Comment by Perksey** [comment]
Hmm I'm not sure. Seeing as glTexParameterI is a pointer, it's probably best we keep it at least a by-reference parameter. If you're passing singular parameters, you might want to use `GL.TexParameter` instead of `GL.TexParameterI`

**Comment by ceranco** [comment]
> Seeing as glTexParameterI is a pointer, it's probably best we keep it at least a by-reference parameter. If you're passing singular parameters, you might want to use `GL.TexParameter` instead of `GL.TexParameterI`

I completely missed that :grimacing:
`GL.TexParameter` is exactly what I was searching for, thanks!
