### ISSUE TITLE
Use same structs for glfw image data

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#139]
Cursors and icons use the same data structure in glfw but different ones in Silk atm. Should be changed to use the same structure in Silk as well in the future.

**Comment by Perksey** [comment]
Slated for 2.0

**Comment by Perksey** [comment]
ICursor and SetWindowIcon now uses the new `RawImage` structure added in Silk.NET.Core as part of my latest PR. Silk.NET.GLFW still uses its own image data structure as `RawImage` uses a byte array, whereas `Image` uses a byte pointer.

**Comment by Perksey** [comment]
Done in #260
