### ISSUE TITLE
Add position to click events

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#140]
- [x] I have definitely checked that there are no proposals for this already in the [proposals folder](https://github.com/Ultz/Silk.NET-Docs)

# Summary of feature
Add the click position as a parameter to click events.

# Comments
The single click event is per definition a delayed event as a single click can only be determined if no second click took place in a given time span. The problem now is that the position may have changed until then so the actual clicked position is not necessarily the position the mouse is at when the click event is raised. This is more relevant the longer the double click time is. So I would like to add the real click position as a parameter to the click event. For consistency reasons I would also add it to the double click event.

In the internal code we already store the position of the first click. But it is not provided in the event. Current workflow is retrieving the current position from the mouse when the click event is raised. But as I said the position may have changed between the first click and the event raising.

**Comment by Perksey** [comment]
Slated for 2.0 as this will be a breaking change, sorry :(

**Comment by Pyrdacor** [comment]
No problem. There are at least workarounds like storing the click position in mouse down event handler and use it in click handler. ;)

**Comment by Perksey** [comment]
@Pyrdacor Unrelated but can you check Discord?

**Comment by Perksey** [comment]
Done in #260
