### ISSUE TITLE
Consider checking in the sources for generated bindings

### ISSUE THREAD

**Issue by tannergooding** [Ultz/Silk.NET#145]
Silk.NET does not currently check in the generated bindings for things like Vulkan or OpenGL.

This presents a couple scenarios that are less than desirable:
* You can't see the bindings without cloning the repository
* You can't open the solution in Visual Studio (or another IDE) and have it "just work"
* You can't trivially diff the API surface between two given releases
* You can't easily perform historical builds
* etc

The generated sources are overall small and Git is highly efficient at compressing the source files and the diffs of the files over time. For example, the current repo in compressed form is only `9.80 MiB` (representing all 397 commits across all 5 branches).
As such, it would be great if Silk.NET could begin checking in the generated bindings and updating them whenever it targets a new baseline version of the respective specs.

**Comment by Perksey** [comment]
The Working Group has decided to check in these files and will implement the change shortly.
