### ISSUE TITLE
Consider adding support for older OpenGL versions (<3.2)

### ISSUE THREAD

**Issue by 8Observer8** [Ultz/Silk.NET#184]
Hello.

I have a notebook with two video cards. The default video card supports maximum OpenGL 3.1. Could I set GLFW for using OpenGL 3.1?

I installed:

`dotnet add package Silk.NET --version 1.2.1`
`dotnet add package Silk.NET.OpenGL.Legacy --version 1.2.1`

But this error occurred when I try to run: `dotnet run`

`Silk.NET.GLFW.GlfwException: VersionUnavailable: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable`

**Comment by Perksey** [comment]
Hi there! Currently, GLFW does not support using older versions as it requires the `WGL_ARB_create_context_profile` extension, a WGL extension that is only available on OpenGL 3.2 or later. Luckily, we have an SDL backend in the works which should hopefully add support for these older versions.

Will leave open for now.

Also, on a side note: you don't need to install the Silk.NET metapackage if you're only using OpenGL and Windowing. You can just grab those two packages `Silk.NET.OpenGL.Legacy` and `Silk.NET.Windowing` (as well as `Silk.NET.Input` if you want to get user input) - that way you only ship the DLLs you need.

**Comment by 8Observer8** [comment]
I deleted all packages from my computer using this command: `dotnet nuget locals all --clear` I deleted ItemGroup from the .csproj file

I installed:
`dotnet add package Silk.NET.OpenGL.Legacy --version 1.2.1`
`dotnet add package Silk.NET.Windowing --version 1.2.1`
`dotnet add package Silk.NET.Input --version 1.2.1`

I want to run this example: https://github.com/Ultz/Silk.NET/tree/master/examples/CSharp/Tutorial%201.1%20-%20Hello%20Window

I typed these commands:
`dotnet restore`
`dotnet run`

But I see again: `Silk.NET.GLFW.GlfwException: VersionUnavailable: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable`

How to use SDL2 instead of GLFW?

**Comment by Perksey** [comment]
SDL support isn't ready yet and won't be ready until 2.0 releases later this year. I recommend looking to use OpenGLES, along with a suitable emulator like Google's ANGLE, so that you can use OpenGLES (including the new-style OpenGL API) over DirectX.

**Comment by Perksey** [comment]
Turns out there was a simple fix, you needed to set the GraphicsAPI.Profile property to Compatiblity. Closing...
