### ISSUE TITLE
Expected 3rd param of KeyDown/KeyUp to be the modifiers

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#185]
The 3rd param of the glfw KeyDown/KeyUp events is the code instead of the modifiers. Is this on purpose? I expected it to be the modifiers. Or do I have to create key modifiers on my own through IsKeyPressed?

**Comment by Perksey** [comment]
Yes this is on purpose. We expect users to check the modifiers themselves. If they need the character with modifiers applied, they can use the KeyChar event.

**Comment by Pyrdacor** [comment]
I was thinking more of key shortcuts like "Ctrl + F" or "Alt + Return" etc. But it's ok if this is the correct behavior. I can create the modifiers on my own.
