### ISSUE TITLE
Flickering window with Window.run()

### ISSUE THREAD

**Issue by Menotdan** [Ultz/Silk.NET#186]
Whenever I open a window with Window.run() it just opens a window where the contents are a flickering portion of my screen at the time of opening the window. The window title is correct, and the open, close, minimize buttons show up.

# Steps to reproduce
- Platform: Desktop (AntiX linux with latest GNOME and Xorg)
- Framework Version: .NET Core 3.1
- API: OpenGL
- API Version: Latest OpenGL version
1. Copied the hello window example
2. Then I ran the code

**Comment by Perksey** [comment]
Resolved in Discord - just need to render stuff
