### ISSUE TITLE
[2.0] Source Link

### ISSUE THREAD

**Issue by HurricanKai** [Ultz/Silk.NET#213]
Providing Source Link + .pdb + deterministic builds will provide the best debugging experience, and it isn't that much work.
See [official guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)

**Comment by HurricanKai** [comment]
I will pick this up once #190 is complete, if approved

**Comment by Perksey** [comment]
Sounds fine to me, @devvoid any objections?

**Comment by Perksey** [comment]
Done in #260
