### ISSUE TITLE
[Maths/Intrinsics] SIMD pseudo random number generator

### ISSUE THREAD

**Issue by HurricanKai** [Ultz/Silk.NET#216]

**Comment by Perksey** [comment]
Doesn't feel necessary but if someone PR'd it in I don't think I would have any objections.

**Comment by HurricanKai** [comment]
Just seen the topic in my feed, and figured that's a really easy thing to do, but may improve someone's experience.

**Comment by Perksey** [comment]
Gonna untriage this for 2.0 as it's not mission critical, but if someone wants to implement it I'll accept it as part of any release.
