### ISSUE TITLE
Way to get my own gameloop going on

### ISSUE THREAD

**Issue by tapir** [Ultz/Silk.NET#217]
Looking at the examples I see that the game loop is structured in a way that doesn't suit my needs (I mainly do mulithreaded stuff)
Is there a possibility to get my own game loop going on? Just a simple for loop where I can poll input, render etc...

**Comment by Perksey** [comment]
Hi there! Thanks for using Silk.NET.

A good start might be checking out [the code for the `Run` method](https://github.com/Ultz/Silk.NET/blob/master/src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs#L44) which is actually an extension method implementing a basic game loop - all of the input-related stuff hooks into either DoEvents or DoUpdate (depending on whether GLFW defines a callback or we have to manually check for changes). Multi-threading obviously gets messy with OpenGL, so make sure you're using MakeCurrent etc when using OpenGL on different threads.

Let me know if you need anything else
