### ISSUE TITLE
How can I hide taskbar icon

### ISSUE THREAD

**Issue by dawiddyrcz** [Ultz/Silk.NET#250]
I can set window borders but i dont now how can I hide taskbar icon? Is this possible?
I want to make window which behaves like mdi window / child window which are not present on taskbar.

**Comment by Perksey** [comment]
Hi there, thanks for using Silk.NET!

It can't be done due to an upstream limitation. Sorry :|

If GLFW gets this functionality we may consider it for a future release, however for now I think this issue is closed.

**Comment by Perksey** [comment]
GLFW doesn't support this still.
