### ISSUE TITLE
Feature Request: Visual Studio Code support

### ISSUE THREAD

**Issue by ZacharyPatten** [Ultz/Silk.NET#273]
### Feature Request

Add `.vscode` folder with extensions, tasks, launches, and (optionally) settings `.json` files so people can run the examples from Visual Studio Code rather than Visual Studio without additional setup.

**Comment by ZacharyPatten** [comment]
I volunteer to add these files if desired.

**Comment by Perksey** [comment]
I don't see why not :D My only concern is with these files becoming out of date as neither myself nor Kai use VSCode.

**Comment by ZacharyPatten** [comment]
Yeah. They can become out of date, but they really help new devs who don't want/have VS or are on Linux. I have example files here:
https://github.com/ZacharyPatten/Towel/tree/master/.vscode

However there are a few things that you may not want to add to your files. Mainly, I apply custom syntax highlighting in my settings folder that you guys may not want.

The main things that will become out are file paths. If you move file paths or change the build target (.NET Core 2.0 -> 3.1 for example) the file path in the launch will need to be updated.

**Comment by HurricanKai** [comment]
We don't check in Rider or VS files, why VSC? I'd be on board with launchSettings as they, like `.editorconfig` are shared across IDEs.

**Comment by Perksey** [comment]
> I'd be on board with launchSettings as they, like .editorconfig are shared across IDEs.

Did not know this. `launchSettings.json` sounds like the way to go then.

**Comment by HurricanKai** [comment]
In regards to Hacktoberfest, to clarify, we would appreciate contribution of `launchSettings.json` file(s) for now.

**Comment by ZacharyPatten** [comment]
Nice :) Sorry I didn't have time to add these when I opened the issue. Glad someone else did.
