### ISSUE TITLE
Consider using our own marshalling APIs (i.e. our own MarshalAs and UnmanagedType)

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#283]
This will allow us to allow extra marshalling options (such as UTF8 strings - we're currently using ANSI where we should be using UTF8).

This would consist of the following
- Adding more SilkMarshal methods to support more string encodings (using `System.Text.Encoding`)
- Adding our own `UnmanagedType` enum
- Adding our own `UnmanagedTypeAttribute`, probably shouldn't use `MarshalAs` as that may mistake P/Invoke users who are also using Silk.NET or SilkTouch-powered bindings
- We should keep support for the regular `MarshalAsAttribute`, as this is ubiquitous and forcing our own may break other projects, such as the ClangSharp SilkTouch backend.

**Comment by HurricanKai** [comment]
I'm not too fond of keeping the "original" marshal as, because we do not support most of its features, so it may be misleading.

**Comment by Perksey** [comment]
The same logic can be applied to Silk.NET.Maths ;)

**Comment by HurricanKai** [comment]
Honestly not sure what you mean

**Comment by Perksey** [comment]
We're not gonna force people into using our maths types if they don't need them like OpenTK does, I reckon we should apply the same principle to the MarshalAs attributes as well.

Also, I think extra work will have to be done in getting ClangSharp to work with our custom attribute, so supporting the old one in addition to the new one will help a lot.

**Comment by HurricanKai** [comment]
I see. Makes sense I guess. Be sure to open an issue for anything you need, even if it can be worked around.

**Comment by Perksey** [comment]
Will do :+1:
