### ISSUE TITLE
Investigate getting Silk.NET to work atop CoreRT

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#284]
Commit [700c15cb](https://github.com/Ultz/Silk.NET/commit/700c15cbcc60d9a8522cd1c13dd58adfed07fd5e) adds a [CoreRT test project](https://github.com/Ultz/Silk.NET/tree/2.0/src/Lab/CoreRTTest) to the 2.0 [Silk.NET Lab](https://github.com/Ultz/Silk.NET/tree/2.0/src/Lab).

Currently, CoreRT can't run Silk.NET projects due to the windowing system unable to resolve a platform. This could be for many reasons, as Silk.NET.Windowing uses a bit of reflection to resolve a platform as well as a custom dynamic loading system for our bindings. The current output is this:
```
Unhandled Exception: System.PlatformNotSupportedException: Couldn't find a suitable window platform. https://docs.ultz.co.uk/Silk.NET/windowing/troubleshooting.html
   at Silk.NET.Windowing.Window.Create(WindowOptions) + 0x8f
   at Tutorial.Program.Main(String[]) + 0xc6
   at CoreRTTest!<BaseAddress>+0x170d177
   at CoreRTTest!<BaseAddress>+0x170d200
```

At some point someone should investigate the cause of this issue as (in theory) everything should be working, the only part where it may be failing is the reflection.
- The static constructor of `Silk.NET.Windowing.Window` calls `TryAdd`, which in turn calls `Assembly.Load` and attempts to reflect through the implementation assemblies to find a platform. __This could be where it's failing__
- The dynamic loading system shouldn't be an issue, as this uses P/Invoke to access kernel32, so there's nothing special going on there unless the issue is that kernel32 can't find glfw3.dll.

That's all the insights I have to hand at the moment.

**Comment by HurricanKai** [comment]
Mostly resolved with #303. I'll keep a look out to make AOT support even better, but this should suffice.
