### ISSUE TITLE
Propose and implement an Input system.

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#3]
# Status
- [x] Awaiting proposal (#16)
- [x] Proposal approved
- [x] Awaiting pull request merge
- [x] Pull request merged and implemented

**Comment by AzyIsCool** [comment]
this needs updating lol

**Comment by Perksey** [comment]
Done

**Comment by devvoid** [comment]
Input.Common has been implemented, but as of now there aren't any implementations of the API yet.
