### ISSUE TITLE
Convert SilkTouch from a Source generator to something more IDE friendly

### ISSUE THREAD

**Issue by HurricanKai** [Ultz/Silk.NET#301]
SilkTouch increases build times by > 50s in large projects. Right now IDEs don't call into SilkTouch, but once they do, on every keypress, opening the Silk.NET solution will probably be almost impossible.

@Perksey any thoughts?

**Comment by HurricanKai** [comment]
Looking at https://github.com/aarnott/CodeGeneration.Roslyn

**Comment by Perksey** [comment]
I hear Uno.CodeGeneration is good

**Comment by Perksey** [comment]
Deemed moot in a meeting.
