### ISSUE TITLE
GetString(StringName.Extensions)

### ISSUE THREAD

**Issue by RichardPreziosi** [Ultz/Silk.NET#313]
# Summary
calling GetString(StringName.Extensions) returns the appropriate string, but results in GLEnum.InvalidEnum.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3
- API: OpenGL
- API Version: OpenGL 3.3.13587 Core
1. Created the GL context, grabbed the version
2. Grabbed the extensions string data to check that shaders are supported.

# Comments
Khronos states that StringName.Extensions is usable only with 'glGetStringi', I assume that inside of Silk it is routing it correctly as it returns the correct value, but the resulting error isn't expected.

**Comment by Perksey** [comment]
This is likely just a driver-specific thing, some drivers are more tolerant than others. I think historically this function was used to fetch extensions, with each extension name being separated using whitespace, however as you said glGetStringi is the correct method these days.

This isn't silk's problem as we don't do any routing or marshalling on top of this. Use the overload of GetString that takes an int and an enum.

**Comment by Perksey** [comment]
Closing due to it being a driver issue and not a Silk.NET one.
