### ISSUE TITLE
Cleanup Repo

### ISSUE THREAD

**Issue by HurricanKai** [Ultz/Silk.NET#326]
there is some stuff laying around, which should be deleted.

**Comment by HurricanKai** [comment]
We should also delete all the packages, since they are largely outdated.

**Comment by Perksey** [comment]
What did you have in mind? No rush to cleanup anything in particular. Will look at GitHub Packages now.

**Comment by Perksey** [comment]
Update: can't delete packages on GitHub Packages

**Comment by HurricanKai** [comment]
I believe we made this issue in one of the meetings :eyes:
I think mostly some CI stuff we no longer use?

**Comment by Perksey** [comment]
Ah yeah there's one folder in build that we can remove. Will do that now and then close.

**Comment by Perksey** [comment]
Done
