### ISSUE TITLE
Consider adding DirectX via a C header parser.

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#33]

**Comment by Perksey** [comment]
Update: BlackCentipede will be doing this using a proprietary C99 to Binder JSON converter, which he's generously letting Ultz use. However, this does mean the community won't be able to regenerate the specifications should we disappear. In that case, we'll use CastXML. We believe that using Crandall's converter instead of an open-source one such as CastXML will improve the reliability of our bindings.

**Comment by john-h-k** [comment]
you can use microsoft/ClangSharp for this? It is open source

**Comment by Perksey** [comment]
Yep, we intend to tack ClangSharp onto our bindings generator once the function pointer output is in.
