### ISSUE TITLE
String marshalling broken

### ISSUE THREAD

**Issue by ThomasMiz** [Ultz/Silk.NET#330]
# Summary
String marshalling in the 2.0.0 preview appears to be broken

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3.1
- API: OpenGL
Call probably any GL function for getting a string, using the overload that returns an already marshalled string object.
glGetActiveAttrib, glGetActiveUniform, etc.
Stack trace example from the Discord discussion: https://media.discordapp.net/attachments/607634593201520651/765756087693475890/unknown.png

I've tried marshalling the strings on my own by using other function overloads and that works fine.

Also, can we please switch all the IntPtr and UIntPtr back to just int and uint?
For example in Silk 1.0 we had `glBufferData(BufferTargetARB, uint, void*, BufferUsageARB)` but in the 2.0 preview there is no overload with an uint, only with UIntPtr.

**Comment by Perksey** [comment]
Fix identified, I'm going to go curl up in a ball and cry for the evening and then suck up to Kai until the end of time for the despicable lie I told him. My apologies.

**Comment by Perksey** [comment]
Complete.
