### ISSUE TITLE
Sharing resources between different GL contexts

### ISSUE THREAD

**Issue by ThomasMiz** [Ultz/Silk.NET#334]
# Summary of feature
Implement a way to share resources between different GL contexts, which would allow for things like rendering something while loading content in the background, instead of halting the window.

**Comment by Perksey** [comment]
Definitely a must-have for 2.0! Possible design:
```diff
  public struct WindowOptions
  {
+ public IGLContextSource SharedContext { get; set; }
  }
```

Notes for possible implementors:
- the IGLContext provided should be checked for compatibility with the current window platform. i.e. a `SdlWindow` can only be created with a context that originated from the SDL backend, and a `GlfwWindow` can only be created with a context that originated from the GLFW backend. **make sure you check for this!**
- on glfw, pass the `WindowHandle*` of the `SharedContext` to `glfwCreateWindow`
- on sdl, make the `SharedContext` current before creating the context of the new window, and then add `GLattr.GLShareWithCurrentContext` to the context attributes.
- please do this work against 2.0. thanks!
