### ISSUE TITLE
Silk with ImGui.NET - Attempted to read or write protected memory

### ISSUE THREAD

**Issue by ScottKane** [Ultz/Silk.NET#339]
I am using the Window sample and trying to integrate ImGui.NET to show the demo window inside a Silk.NET window. I am experiencing memory issues which I assume is because I am trying to render the gui in the wrong place.

``` c#
unsafe private void Render()
{

    _data.GL.Clear((uint)ClearBufferMask.ColorBufferBit);
    _data.GL.BindVertexArray(_vertexArray);
    _data.GL.UseProgram(_shader);
    _data.GL.DrawElements(PrimitiveType.Triangles, (uint)_indices.Length, DrawElementsType.UnsignedInt, null);

    ImGui.ShowDemoWindow();
}
```

ImGui.NET has examples of how to do this with Veldrid (Veldrid also has extensions for an ImGuiRenderer to make it easier).

**Comment by Perksey** [comment]
Sadly it isn't that simple to hook in ImGui.NET. Luckily, we've done all the heavy lifting in the [SilkExtensions](https://github.com/Ultz/SilkExtensions) repo (pretty obscure and hard to find sorry, we're considering merging it into the main repo dw)

In there is a working sample using Silk.NET.OpenGL for windowing

**Comment by ScottKane** [comment]
Oh awesome, I hadn't come across that repo. Thanks for the quick reply

**Comment by ScottKane** [comment]
Maybe you could just publish it as Silk.NET.Extensions.ImGui or something

**Comment by Perksey** [comment]
It's published today as Ultz.SilkExtensions.ImGui, but yeah we need to discuss whether to bring it together in the main repo.
