### ISSUE TITLE
BadImageFormatException when calling glBufferData with ReadOnlySpan<T>

### ISSUE THREAD

**Issue by Nihlus** [Ultz/Silk.NET#342]
# Summary
When calling glBufferData with a ReadOnlySpan<T> as the data input, the runtime throws a BadImageFormat exception and terminates execution. This appears to be due to the use of generic pointers, but I'm not entirely sure.

# Steps to reproduce
- Platform: Desktop (Linux, x64, Radeon RX Vega, VEGA10, DRM 3.35.0, 5.4.0-52-generic, LLVM 10.0.0)
- Framework Version: .NET Core 3.1
- API: OpenGL
- API Version: OpenGL 3.3 Core (requested), OpenGL 4.6 Core (available)
- Silk.NET Version: 2.0.0-preview2

1. Create a buffer with some data
2. Pass it to glBufferData as a ReadOnlySpan<T>

# Comments
A workaround is to convert the span to a fixed `void*` and pass that instead, which works as expected.

![image](https://user-images.githubusercontent.com/2340428/98445833-1891b280-211a-11eb-9e5c-ea368f625697.png)

**Comment by Perksey** [comment]
Will try and reproduce this in a bit. What Linux distro are you on?

**Comment by Nihlus** [comment]
Linux Mint 20.1, so it's Ubuntu-based.

**Comment by Perksey** [comment]
Assigning to @HurricanKai who will be implementing a marshaller which converts generic pointers to void pointers before calling the underlying function pointer as part of the `feature/ios` branch.

**Comment by Perksey** [comment]
Fixed in 2.0 Preview 3
