### ISSUE TITLE
WindowBorder.Fixed does not always avoid window resizing

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#344]
# Summary
I used `WindowBorder.Fixed` as a window option which works fine most of the time. But recently I used an HDMI switch to switch between laptop and PC. After switching I guess the screen's resolution is re-calibrated somehow and this seems to cause a window resize even if the mentioned option is set. I don't know if this is a glfw bug.

My workaround is to handle the `Resize` event and set the window's `Size` property again if the size differs from the expected one. If it is a glfw issue or something that could not be fixed at all, this workaround inside Silk might be an option.

**Comment by Perksey** [comment]
WindowBorder.Fixed doesn't guarantee no window resizes, it just ensures that the user can't resize the window by dragging its border.

**Comment by Pyrdacor** [comment]
Ok so my workaround is fine then I guess. ;)
