### ISSUE TITLE
Expose HWND of window

### ISSUE THREAD

**Issue by azeno** [Ultz/Silk.NET#347]
# Summary of feature
It would be nice if the `IWindow` interface could expose the native window handle (for example `HWND` on windows). The current `Handle` property isn't doing that.

# Comments
The windowing and input abstraction of this project look very nice. In a quick test I wanted to setup a window without a pre-configured graphics context and instead use the Stride API to render into it. However that won't work unless I can somehow access the HWND.

I also looked at the 2.0 preview with the hope that the SDL bindings would have the handle but it seems to be missing there also - `SDL_GetWindowWMInfo` was the method I was looking for.

**Comment by Perksey** [comment]
Could probably sneak this into Preview 3 as I'm releasing that tonight, but it will likely be SDL-specific at least initially.

**Comment by azeno** [comment]
That would be great!

**Comment by Perksey** [comment]
Oh wow I didn't realise we missed GetWindowWMInfo, will fix and provide a way to reuse the SDL instance Silk.NET.Windowing.Sdl makes internally.

**Comment by Perksey** [comment]
Added in 2.0 Preview 3. APIs added to help you out with this venture:
- Silk.NET.Windowing.Sdl.SdlWindowing.GetExistingApi
- Silk.NET.Windowing.Sdl.SdlWindowing.GetSysWMInfo
- Silk.NET.Windowing.Sdl.SdlWindowing.GetHandle

**Comment by azeno** [comment]
Thanks a lot! As you can see it also exposed a bug in Stride. For reference and if anyone is interested, here is the code to have Stride rendering into the window. Only tested on Windows 10 and DirectX11.

    // SDL window gives access to HWND
    Window.PrioritizeSdl();

    // Create a plain window
    var options = WindowOptions.Default;
    options.ShouldSwapAutomatically = false;
    options.API = new GraphicsAPI(ContextAPI.None, ContextProfile.Core, ContextFlags.Default, default);

    using var window = Window.Create(options);
    window.Initialize();

    // Setup the graphics device
    using var graphicsDevice = GraphicsDevice.New(DeviceCreationFlags.BgraSupport, GraphicsProfile.Level_11_0);
    var graphicsContext = new GraphicsContext(graphicsDevice);
    var commandList = graphicsContext.CommandList;

    // Setup the swap chain
    var hwnd = SdlWindowing.GetSysWMInfo(window).Value.Info.Win.Hwnd;
    var presentationParameters = new PresentationParameters()
    {
        DeviceWindowHandle = new WindowHandle(default, window, hwnd),
        BackBufferWidth = window.Size.Width,
        BackBufferHeight = window.Size.Height,
        PresentationInterval = PresentInterval.One
    };
    using var presenter = new SwapChainGraphicsPresenter(graphicsDevice, presentationParameters);

    while (!window.IsClosing)
    {
        window.DoEvents();

        presenter.BeginDraw(commandList);
        commandList.SetRenderTarget(presenter.DepthStencilBuffer, presenter.BackBuffer);
        commandList.Clear(commandList.RenderTarget, new Stride.Core.Mathematics.Color4(0.1f));
        presenter.EndDraw(commandList, present: true /* Doesn't seem to work */);

        presenter.Present(); // Therefor call it manually
    }

**Comment by haolange** [comment]
no Glfw support?

**Comment by Perksey** [comment]
@haolange 2.0 shipped with native API support, see the `window.Native` API. That didn't exist back then.
