### ISSUE TITLE
VulkanTriangle throws "KHR_surface extension not found."

### ISSUE THREAD

**Issue by dmsch** [Ultz/Silk.NET#349]
# Summary
The VulkanTriangle project throws a NotSupportedException("KHR_surface extension not found.")

# Steps to reproduce
- Platform: Desktop, Windows 10 Pro (Version 2004)
- Framework Version: .NET Core 3.1.302
- API: Vulkan
- API Version: Vulkan 1.2

1. First I did this
- Clone master, run generator.bat

2. Then I did this
- Build and run src/Lab/VulkanTriangle.csproj

**Comment by HurricanKai** [comment]
That suggests your hardware doesn't have the necessary Vulkan extension. What CPU/GPU do you have?

**Comment by dmsch** [comment]
@HurricanKai Intel UHD Graphics 620, and Radeon RX 550X  (Lenovo ThinkPad)

**Comment by Perksey** [comment]
Ensure you have the Vulkan SDK installed. If you don't, you should probably install it. Otherwise, take a look at the vkconfig.exe tool to see if the extension pops up in there.

**Comment by dmsch** [comment]
The Vulkan SDK is installed and I also updated the drivers.
vkconfig.exe shows me the KHR_Surface extension.
Maybe the wrong physical device  (the discrete GPU) is selected?

![image](https://user-images.githubusercontent.com/43646834/99772465-2298b580-2b0b-11eb-818d-fb1d26e9e7ca.png)

**Comment by dmsch** [comment]
Fixed this issue and another one (out of bounds when iterating over presentMode) in #354
