### ISSUE TITLE
missing dispose call

### ISSUE THREAD

**Issue by nablabla** [Ultz/Silk.NET#355]
# Summary
there seems to be missing a dispose call in the glfw events class

# Steps to reproduce
look here, in the Dispose() method the event GlfwCallbacks.ScrollCallback Scroll was left out in 
https://github.com/Ultz/Silk.NET/blob/master/src/Input/Silk.NET.Input.Desktop/GlfwEvents.cs

# Comments
I am not sure

**Comment by Perksey** [comment]
Feel free to submit a pull request.

**Comment by Perksey** [comment]
Fixed in 2.0 Build 601
