### ISSUE TITLE
No files named generator.bat or generator.sh (to generate the bindings)

### ISSUE THREAD

**Issue by erikmartinessanches** [Ultz/Silk.NET#380]

**Comment by Perksey** [comment]
To be able to fix this, we need to agree on a [new readme](https://github.com/Ultz/Silk.NET/tree/feature/new-readme) which we haven't done at the moment.

Assigning Kai as he had some objections to the currently proposed readme header.

**Comment by Perksey** [comment]
Closed in `a73a883` with a temporary edit as we haven't settled on a complete readme overhaul quite yet!
