### ISSUE TITLE
C# 8 Nullable Support

### ISSUE THREAD

**Issue by HurricanKai** [Ultz/Silk.NET#39]
# Summary of feature
C# Nullable to be supported / used in the libary. C# 8 is just around the corner and this would improve ease of use with C# 8. Personally I don't feel like this is slowing development of Libs at all.

# Comments

**Comment by HurricanKai** [comment]
Together with this, it might make sense to implement `readonly` members. Skimming over some of the code there seem to be a lot of cases where this could be applied, and I don't see downsides to using it (besides that It'll take time to get used to it)

**Comment by HurricanKai** [comment]
Also, If applicaple, `Index` and `Range` overloads could be added.

**Comment by Perksey** [comment]
> 
> 
> Also, If applicaple, `Index` and `Range` overloads could be added.

To which methods?

**Comment by HurricanKai** [comment]
All indexers currently using `int`

**Comment by Perksey** [comment]
Ah okay. Would love some help with this! Currently, I'm not going to be able to work on Silk for a little bit as I have other Ultz projects I need to catch up on.

**Comment by Perksey** [comment]
This has proven to be quite the grueling task. I've decided to move this to a future release, as the binder is currently undergoing some heavy refactorings.

**Comment by Perksey** [comment]
Closed in #45

**Comment by Perksey** [comment]
This was prematurely closed! In 2.0, we'd like to add nullability attributes to the following codebases:
- [ ] Maths
- [ ] Input
- [ ] Windowing
- [ ] Core

**Comment by Perksey** [comment]
Done in #260
