### ISSUE TITLE
Malformed XML in Silk.NET.Windowing.Sdl.Android.targets

### ISSUE THREAD

**Issue by charm137** [Ultz/Silk.NET#393]
Minor typo [here](https://github.com/Ultz/Silk.NET/blob/82e27dcea6083f78d8a615deb2ee5ff97f5f5ec8/src/Windowing/Android/Silk.NET.Windowing.Sdl.Android/Silk.NET.Windowing.Sdl.Android.targets#L1) ("version" spelled as "verison") causing MSBuild to brick the build (and .csproj loading issues) when the nuget package for Silk.NET.Windowing.Sdl.Android is included in a user-project.

**Comment by Perksey** [comment]
THAT WAS WHAT WAS CAUSING IT?!?!?
