### ISSUE TITLE
Small elapsed time on Render() when vsync is enabled

### ISSUE THREAD

**Issue by ThomasMiz** [Ultz/Silk.NET#394]
# Summary
When VSync is on, the elapsed time passed to the Render() method is typically a very low value on some machines (in mine, 0.00001 to 0.001, which is waaay lower than the ~0.016 expected with a window configured to 60fps).

(When VSync is turned off, in my machine the elapsed time is around 0.016 as expected).

# Steps to reproduce
- Platform: Desktop
- NET Version: .NET 5
- API: OpenGL 3.3

I set up a small project to try to reproduce the problem. To run, download the 2.0 release Silk.NET.OpenGL, Windowing and Input packages and run a project with nothing but [this Program.cs file](https://cdn.discordapp.com/attachments/607634593201520651/795043831732764742/Program.cs) (don't worry, it's quite small 😉)

# Comments
Since this problem doesn't seem to be happening to anyone but me, I will investigate this issue further.

**Comment by ThomasMiz** [comment]
Fixed by PR #395

**Comment by thargy** [comment]
Note.  the `WindowOptions.Vsync` property sets the `SwapInterval` for OpenGL.  It therefore, doesn't have any effect automatically on Vulkan, other than ignoring the `FramesPerSecond` property, which can lead to unbounded render calls if the implementor has not enabled VSync on Vulkan. (See [this StackOverflow answer for how to implement VSync on Vulkan](https://stackoverflow.com/questions/36896021/enabling-vsync-in-vulkan))

**Comment by HurricanKai** [comment]
Note on Vulkan VSync: The render calls are still unbound, and we may need to fix this. The basic approach to VSync in Vulkan is using `VK_PRESENT_MODE_MAILBOX_KHR` or `VK_PRESENT_MODE_FIFO_RELAXED_KHR` which don't do any VSync functionality. They just specify when images are presented to the screen. This can then be waited for using fences/semaphores.
not 100% sure how events in C# behave right now, but it may be possible that we call the Render functions so quickly that a queue of event handlers form that just wait for the semaphore images to become available.
For similar reasoning, I think we need to consider always enabling "VSync" (skipping the check) when using vulkan - we don't do any handling on Vulkan so I don't think it's useful to pretend we do.
If the user chooses to initialize their swapwchain with `VK_PRESENT_MODE_IMMEDIATE_KHR` (which is not the default, and not even guaranteed available on all devices) they probably have reasons to do so. Us checking whether they run to fast is likely not helpful. (Simple use case: testing performance, but many others are possible)

**Comment by thargy** [comment]
According to [this article](https://software.intel.com/content/www/us/en/develop/articles/api-without-secrets-introduction-to-vulkan-part-2.html?language=en#_Toc445674479) `VK_PRESENT_MODE_FIFO_RELAXED_KHR` may result in tearing if the render rate is slower than the refresh rate, and it is not guaranteed on all devices, unlike `VK_PRESENT_MODE_FIFO_KHR` where you're forced to wait until the image is available (i.e. a Vsync has occurred).  `VK_PRESENT_MODE_MAILBOX_KHR` (equivalent to triple buffering) is recommended when available, followed by fallback to `VK_PRESENT_MODE_FIFO_KHR` (which should be available on compliant drivers).

As you say, `VK_PRESENT_MODE_IMMEDIATE_KHR` is equivalent to 'VSync off' where available.

> For similar reasoning, I think we need to consider always enabling "VSync" (skipping the check) when using vulkan - we don't do any handling on Vulkan so I don't think it's useful to pretend we do.

I would have thought we'd do the opposite, i.e. set the option on the view to off, this will then respect the `FramesPerSecond` option when set:

```csharp
if (VSync || ((Stopwatch.GetTimestamp() - _renderTimestamp) >= _renderPeriod)) ...
```

> they probably have reasons to do so.

Most commonly, this is used during development to see the 'maximum refresh rate available', and by devs and gamers for performance testing.

> Us checking whether they run to fast is likely not helpful.

If `FramesPerSecond` is set on the view it is anticipated you'd clamp render to being no faster than that, I don't think Vulkan should impact that behaviour.  If someone wants to run 'as fast as possible' they should leave that at `0`, set `VSync` off, and use `VK_PRESENT_MODE_IMMEDIATE_KHR`.

Personally, I don't use a `VSync` property, just an `FPS` where -ve means VSync, 0 means unbounded, +ve means FPS.

**Comment by HurricanKai** [comment]
Makes sense to me - fair point. I appear to have the modes mixed up, sorry about that.
