### ISSUE TITLE
Regression in Silk.OpenAL

### ISSUE THREAD

**Issue by Nihlus** [Ultz/Silk.NET#414]
# Summary
During the 2.0 previews, `_alContextApi.OpenDevice(null);` worked as expected and selected the default device. On the 2.1 release, the call to the OpenDevice method (using a null argument) fails with a null pointer exception. 

The stack trace suggests this error originates from a string marshalling operation, which should not be neccesary in the case of a null value.

# Steps to reproduce
Call `OpenDevice` with a null argument.

**Comment by HurricanKai** [comment]
That's interesting. I don't recall changing anything regarding string marshalling.
Definetly a bug though. Will fix soon.

**Comment by HurricanKai** [comment]
I believe, as a workaround, `""` should be equal to `null` for this purpose.

**Comment by Perksey** [comment]
`nullptr` is needed - `""` would allocate a valid string.
