### ISSUE TITLE
NuGet Packages in debug build?

### ISSUE THREAD

**Issue by Reaper1121** [Ultz/Silk.NET#416]
Hello, I've recently started working on a peformance critical C# library and I stumbled upon this library which meets my criteria perfectly, a day later I noticed that Silk.NET has optimizations disabled because this was built with a Debug configuration, Silk.NET focuses on performance yet having JIT optimizations disabled hurts the performance in production use drastically which makes it one of the slowest bindings libraries, why is that? I would expect for a NuGet package in "Release" build to be published.

**Comment by Perksey** [comment]
This is a known issue and will be fixed in our update on the first week of March.

**Comment by Perksey** [comment]
Fixed in 2.2.
