### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#49]
- [ ] EGL window platform (for Android) - Silk.NET.Windowing.Android
- [ ] EAGL window platform (for Apple) - Silk.NET.Windowing.Apple

**Comment by swoolcock** [comment]
Did you have any initial plans or designs for this?  Manually handling windows, input, etc. for each mobile platform seems like reinventing the wheel when you can bind to something like SDL2# and get both of them for free.

Note that you're going to want to be API-agnostic too.  EGL/EAGL only applies for GLES, it's fairly trivial to create a Metal `UIView` once Silk.NET has Metal bindings.  I don't have experience with Vulkan under Android but I imagine it would mostly be a custom activity or canvas.

**Comment by Perksey** [comment]
Yeah I suppose our mistake was opting to use GLFW where it doesn’t have mobile support. You’re not wrong though, SDL does have greater support and we could probably create an SDL backend and allow the user to pick between GLFW and SDL, using SDL by default on platforms where GLFW isn’t supported.

**Comment by Perksey** [comment]
Closing, as this is pretty much tracked by #182 now
