### ISSUE TITLE
Mouse movement event in IMouse

### ISSUE THREAD

**Issue by alkalinethunder** [Ultz/Silk.NET#56]
- [x] I have definitely checked that there are no proposals for this already in the [proposals folder](https://github.com/Ultz/Silk.NET-Docs)

# Summary of feature
There should be a way to receive an event when the mouse cursor moves and get the position and relative movement of the mouse cursor in the event.

# Comments
Guess this was overlooked, I noticed `IMouse` doesn't have a `MouseMove` event or anything.  Hard to write a UI framework if you can't see where the mouse is :P

**Comment by Perksey** [comment]
Haha, thanks for logging this! Will be done for preview 3.
