### ISSUE TITLE
GL.GetShaderInfoLog calls return a string filled with whitespace instead of the expected log.

### ISSUE THREAD

**Issue by maxilevi** [Ultz/Silk.NET#60]
# Summary
GL.*InfoLog calls return a string filled with whitespace instead of the expected log.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Standard 2.0 / .NET Framework 472

1. Create a GLSL program with syntax errors
2. Compile it and retrieve it's compilation log using GetShaderInfoLog
3. GetShaderInfoLog returns string full of whitespace with no characters.

# Comments
It might have to do with how the string is marshalled.

**Comment by Perksey** [comment]
Confirmed fix in #58
