### ISSUE TITLE
Missing/Wrong mapped keys on Xbox 360 Wireless

### ISSUE THREAD

**Issue by mikart143** [Ultz/Silk.NET#67]
# Summary
I noticed that some keys are not mapped correctly to names.
Button number 11 (counting from zero) is responsible for DPadUp but it s not correct. When i click DPadRight then this button is true.
There is not a a DPadLeft.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3
1. First I did this
I created from my .Net Standard 2.1 Library
2. Then I did this
Then I called function responsible for detecting buttons

# Comments
There is list of detected buttons
First collumn is index, second current state, last is name of button
> 0 False A
1 False B
2 False X
3 False Y
4 False LeftBumper
5 False RightBumper
6 False Back
7 False Start
8 False Home
9 False LeftStick
10 False RightStick
11 False DPadUp
12 False DPadRight
13 False DPadDown

**Comment by Perksey** [comment]
Hi there, thanks for using Silk.NET!

I've made PR #68 to fix this problem, can you please try version `1.0.0-preview420191124.1` on the experimental feed to see if this fixes your issue?

**Comment by mikart143** [comment]
Nothing has changed. Still getting DPadRight as DPadUp. There is also no DPadLeft
