### ISSUE TITLE
Add built-in support for click/doubleclick

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#78]
The input layer only has mouse up and down events. Double clicks are a very common use case. At the moment every Silk user is forced to implement this functionality on its own. A general built-in support is much appreciated.

Adding events for Click and DoubleClick would be nice.

**Comment by Perksey** [comment]
We're currently discussing this in our Discord server trying to figure out an optimal way to implement this. You're welcome to join us, though iirc in our emails you said you're not into Discord so no biggie :D

**Comment by Pyrdacor** [comment]
I implemented this for my project here: https://github.com/Pyrdacor/freeserf.net/blob/2.0/Silk.NET.Window/Window.cs

It's maybe not the best solution but maybe it's a good start. I'm not sure if the timer approach is necessary or good but that's how Microsoft used to implement their double click logic afaik.

A huge problem is that many windows managers allow to setup the double click delay. It's important to use that value if it is present because users expect that setting to be used in applications. There is `SystemInformation.DoubleClickTime` but this is for winforms only. A good default value would be 500ms. I think the best approach would be to make the double click time configurable so we don't need to care about OS/Window manager settings.

**Comment by Perksey** [comment]
Here's a pseudocode proposal that void came up with and is likely the one we're gonna roll with
```
if CurrentMouseButton == LastMouseButton
  if (CurrentTime - LastMouseButtonTime) >= DoubleClickTime
    if (distance_between(LastMouseButtonLocation, CurrentMouseButtonLocation) <= DoubleClickRange)
      OnDoubleClick?.invoke();
      return;

OnMouseDown?.invoke();
```

**Comment by Pyrdacor** [comment]
Do you also plan to add a Click event? Would make sense. A click is a mouse down that is no double click. And here comes the problem with the mentioned pseudo code. You can't raise a click event until you know it's not a double click and you have to raise a click event if two clicks exceeded the max delay. So clicks and double clicks are connected in their logic. With this in mind it is a bit harder than that. Hence the timer approach.

**Comment by Perksey** [comment]
cc @devvoid

**Comment by Pyrdacor** [comment]
@Perksey @devvoid 

I thought about something like this pseudo code:

    OnMouseDown
    {
        raise mouse down event // can be raised independent of clicks

        if (isFirstClick is true or firstClickButton is not button)
        {
            // this is the first click with the given mouse button
            stop the doubleClickTimer

            if (isFirstClick is false) // and so: firstClickButton is not button
                raise single click event with firstClickButton

            call ProcessFirstClick
        }
        else
        {
            // this is the second click with the same mouse button

            if (doubleClickTimer is running)
            {
                // we're inside the double click time

                stop the doubleClickTimer

                if (click distance was in range)
                {
                    // clicked in time and in range -> double click
                    raise double click event
                    set isFirstClick to true
                }
                else
                {
                    // clicked in time but outside range -> normal click
                    // the second click will be another "first click"
                    raise single click event
                    call PerformFirstClick
                }
            }
            else
            {
                // DoubleClickTimer_Elapsed should have handled the first click
                // now process the current click as a new "first click"
                call ProcessFirstClick
            }
        }
    }

    ProcessFirstClick
    {
        // is called for every "first click"
        set isFirstClick to false // so the next click is not the first
        set firstClickButton to button
        start the doubleClickTimer
    }

    DoubleClickTimer_Elapsed
    {
        // elapsed means -> no second click in the max double click time
        stop the doubleClickTimer
        raise single click event
        reset isFirstClick back to true
    }

**Comment by Perksey** [comment]
I've come to the conclusion that I don't care as long as Void comes up with something that works :) Though you're welcome to chip in reviewing the PR once it's ready for review.

**Comment by Pyrdacor** [comment]
Sure

**Comment by devvoid** [comment]
Your pseudocode is roughly what I was thinking about doing. I don't have time for a PR right now, I'll be busy with a game jam until next week, but if you can do a PR for this I'd really appreciate the help!

**Comment by Perksey** [comment]
> but if you can do a PR for this I'd really appreciate the help!

We're currently gearing up for Preview 4's release. Please get any PRs you're considering doing open as WIP by tomorrow evening otherwise they won't make it into Preview 4!

**Comment by Pyrdacor** [comment]
Sorry guys but I'm on vacation till Sunday. So it won't make it into preview 4 unfortunately. But I can help to implement it next week or so.

**Comment by Perksey** [comment]
Ah no worries, it'll be in preview 5 and/or 1.0.

**Comment by Perksey** [comment]
@Pyrdacor If you're still up for making a PR will be happy to review it :P

**Comment by Pyrdacor** [comment]
If I only had some time for it. :D I will try to make a PR soon. But if you or Void have some time for it, then go for it instead.

**Comment by Perksey** [comment]
We're both pretty tied up with other projects at the moment - I only work on Silk.NET when I've got nothing else to do between lessons at school and right now my primary focus is bug fixes.

**Comment by Pyrdacor** [comment]
Ok I'm glad to help. Hopefully soon a time slot will show up. :)

**Comment by Perksey** [comment]
Awesome, thanks in advance!
