### ISSUE TITLE
Add/use OnXYZ event methods instead of raising events directly

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#79]
# Summary of feature
Add protected virtual OnXYZ methods for window events. This way users can override those methods in custom derived window classes and control the event emission by call the base.OnXYZ method or not.

The GlfwWindow implementation will basically call the OnXYZ methods instead of invoking the events directly. The default implementations of the OnXYZ methods will just raise the associated event.

# Example of implementation
```C#
    // part of GlfwWindow.cs
    ...
    var delta = _renderStopwatch.Elapsed.TotalSeconds;
    
    OnRender(delta); // changed from Render?.Invoke(delta);
    
    if (ShouldSwapAutomatically)
    {
        SwapBuffers();
    }
    ...
    
    // somewhere else in GlfwWindow.cs
    protected virtual void OnRender(double delta)
    {
        Render?.Invoke(delta);
    }
```

# Use case
A custom user window may handle the render logic internally (by overriding the OnRender method) but it may want to prevent populating the Render event to the outside or only do so based on some internal conditions.

This is also handy if it should be ensured that the additional logic is executed before the event is consumed by someone else. The developer of the custom window can call base.OnXYZ after his additional code.

```C#
    // part of MyCustomWindowClass
    protected override void OnRender(double delta)
    {
        // do some render related stuff that should be done
        // before anyone is notified about the event ...
        base.OnRender(delta); // raise the event through base method
    }
```

# Implementation

I could implement this very quickly with a PR if you want me to.

**Comment by Perksey** [comment]
In the first ever builds of Silk.NET this is actually how we did things, but we deduced it doesn’t fit well with our dependency injection model. Don’t get me wrong, we could do it, but it’s an unnecessary complication and the events already work fine.

If needed, we can add logic to the existing events so you can cancel further emissions but for virtual methods, we’ve been down this road before and it just doesn’t work well with the API we’ve already forged.

**Comment by Pyrdacor** [comment]
As long as the use cases can be handled in a suitable way I'm ok with different approaches. Conditional event emission and ensurance of custom code execution before event emission are some use cases that may be desirable.

Maybe the time will show if this behavior is a broadly needed feature or not. Until then you may close this issue here. For my current project I get around it with ease.

**Comment by Perksey** [comment]
Yeah, generally we expect the user to wrap the events anyway as there are few cases where a whole engine will need direct access to the window events.
