### ISSUE TITLE
actual examples

### ISSUE THREAD

**Issue by MrGrak** [Ultz/Silk.NET#81]
Silk looks really interesting, but the examples provided (at the tike of my posting) are copied and pasted console.writeLine("hello world") examples. Where might I be able to find actual useful Silk examples?

Thanks

**Comment by Perksey** [comment]
Hey there! Yeah sorry about that, we're working on an in-depth tutorial series but it really does take time. We have a couple of test applications in the [Silk.NET Lab](https://github.com/ultz/silk.net/tree/master/src/Lab) that can be used as examples, this includes 2 applications that produce a triangle in both OpenGL and Vulkan, an application we use for testing our input system, and a blank window app.

These are all minimal examples but realistically once you know how to interface with the native APIs, it's all just simple OpenGL knowledge - most OpenGL tutorials are transferrable to Silk.NET.

Let me know how you get on!

**Comment by MrGrak** [comment]
Thanks, I'll take a look at them. It may be better to remove the examples folder until they are ready. Thanks again.
