### ISSUE TITLE
Additional windows do not properly close

### ISSUE THREAD

**Issue by xposure** [Ultz/Silk.NET#82]
# Summary
Can not close additional windows created. Messing around with a IMGUI library and was trying to implement something like Viewports from Dear IMGUI where it creates windows on the fly to support dragging around outside of the main window.

If you close the smaller window the `IsClosing` flag is set to true, but it never actually closes.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET Core 3

```
  static void Main(string[] args)
        {
            var windowOptions = new WindowOptions();
            windowOptions.Size = new System.Drawing.Size(800, 600);
            windowOptions.Title = "Hello World";

            var mainWindow = Window.Create(windowOptions);
            var windows = new List<IWindow>();
            windows.Add(CreateWindow("test", 200, 200));

            mainWindow.Open();
            while (!mainWindow.IsClosing)
            {
                mainWindow.DoEvents();
                mainWindow.DoUpdate();
                mainWindow.DoRender();

                for (int i = windows.Count - 1; i >= 0; i--)
                {
                    var it = windows[i];
                    if (it.IsClosing)
                    {
                        it.Close();
                        //     windows.RemoveAt(i);
                    }
                    // else
                    {

                        it.DoEvents();
                        it.DoUpdate();
                        it.DoRender();
                    }
                }

                System.Threading.Thread.Sleep(16);
            }

        }

        public static IWindow CreateWindow(string title, int width, int height)
        {
            var windowOptions = new WindowOptions();
            windowOptions.Size = new System.Drawing.Size(200, 200);
            windowOptions.Title = "Hello World";


            var window = Window.Create(windowOptions);
            window.Open();
            return window;
        }
```

**Comment by Perksey** [comment]
Hey there! Nice to see that you're having a go at your own render loop, and I'm actually quite interested to see how ImGui works with Silk.NET ;)

As you can see in [the default game loop](https://github.com/Ultz/Silk.NET/blob/master/src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs#L52), `Reset` is called instead of `Close`, as this just sets IsClosing to true.

This is obscure functionality, I know, but we should probably better document this.

```diff
if (it.IsClosing)
{
-    it.Close();
+    it.Reset();
}
```

**Comment by Perksey** [comment]
Side note: We've discussed making a WindowManager in an extension, so that multiple windows can be easily supported. I'll try and draw up an API proposal for this at some point.

**Comment by Perksey** [comment]
I've created PR #89 to add a WindowManager class that will hopefully make it easier to manage multiple windows in Silk.NET. If all goes well, this will be part of Preview 4. In the meantime, just copy and paste WindowManager.cs into your project and it should work wonders.
