### ISSUE TITLE
Make switching from fullscreen to window possible

### ISSUE THREAD

**Issue by Pyrdacor** [Ultz/Silk.NET#98]
At the moment when switching to fullscreen a GLFW monitor is set. When trying to return to a different window state (Normal, Minimized, Maximized) the monitor is still set and therefore fullscreen mode will remain.

It would be nice to allow switching back from fullscreen to window. I guess it could be done by setting the monitor back to null/0 in the mentioned case.

**Comment by Perksey** [comment]
This may be a limitation with GLFW - I’ll check when I get home, but you could use the Reset and Open methods to recreate the window in windowed mode.

**Comment by Pyrdacor** [comment]
This should be possible with glfw. The docu for `glfwSetWindowMonitor` says:

> When a window transitions from full screen to windowed mode, this function restores any previous window settings such as whether it is decorated, floating, resizable, has size or aspect ratio limits, etc.

And the docu for the second parameter `monitor` states:

> The desired monitor, or NULL to set windowed mode.

**Comment by Pyrdacor** [comment]
> 
> 
> This may be a limitation with GLFW - I’ll check when I get home, but you could use the Reset and Open methods to recreate the window in windowed mode.

This should not be necessary. I guess the glfw functionality handles this without the need for recreating the window. I don't want to recreate the window as switching between modes should be possible on-the fly while my game is running. And I think this is possible with glfw.

**Comment by Perksey** [comment]
Resolved in #102

**Comment by aybe** [comment]
I'm afraid it's not, not all cases do work: https://github.com/dotnet/Silk.NET/issues/1094

**Comment by Pyrdacor** [comment]
I guess the problem is that the `nonFullscreenPosition/Size` values are only updated when switching to `WindowState.Normal` and not `Maximized`.
