### ISSUE TITLE
Consider fixing typo in announcement

### ISSUE THREAD

**Issue by Inzanit** [Ultz/Silk.NET#99]
# Summary
Ourselves was spelt incorrectly in the 2020 announcement.

# Steps to reproduce
- Platform: All
- Framework Version: Chrome
1. Opened GitHub
2. Browsed Issues on Ultz/Silk.NET
3. Viewed #96 
4. Read "outselves"
5. Immediately fell out my chair.

# Comments
Literally unreadable.

**Comment by Perksey** [comment]
Hi there, thanks for looking at Silk.NET's 2020 announcement! I agree these minor, occasional issues within the announcement might make it `unreadable` as it were. I shall address said issues right away. Thanks :D

**Comment by Perksey** [comment]
This issue has been resolved, thanks again for bringing this to my attention!
